language: ruby
before_script:
  - cp config/application{.example,}.yml
  - cp config/database{.example,}.yml
  - bundle exec rake db:create db:schema:load
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
rvm:
  - 2.1.2
branches:
  only:
    - master
notifications:
  campfire: collectiveidea:3c3f07431323f476b2fa69acb37c040ebe7f8f36@109379
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
addons:
  code_climate:
    repo_token: 9510623626e89d9c5d7ac29e7dc642a1e814626f9848ecd90543039bdf68efd1
  postgresql: 9.3
services:
  - elasticsearch
cache: bundler
before_deploy:
  - git fetch --unshallow
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: Xos6xF/UV4Nqv/oQC3a2xavy/hhyKLgGOmMJ59DUUUSbNPztdgGpR3J1y5jiSzTN5im1ux5Zx5EClmTSR4fNO63yZM2o00NGzk0HGicf35pru7K2g8ei5WJyDu5thz0Z7t9uHQRwnDKX6Ds9+ksgk1PcqUfMXTVT4nUtSalmkiU=
  app:
    master: castnotice-staging
  on:
    repo: collectiveidea/castnotice
    branch: master
  run:
    - "rake db:migrate"
    - restart
