language: ruby
before_script:
  - cp config/application{.example,}.yml
  - cp config/database{.example,}.yml
  - bundle exec rake db:create db:schema:load
rvm:
  - 2.0.0
branches:
  only:
    - master
notifications:
  campfire: collectiveidea:3c3f07431323f476b2fa69acb37c040ebe7f8f36@109379
  webhooks:
    urls:
      - http://buildlight.collectiveidea.com/
    on_start: true
addons:
  code_climate:
    repo_token: 9510623626e89d9c5d7ac29e7dc642a1e814626f9848ecd90543039bdf68efd1
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: Wa7cU7phnmdDMGRZDK4B7giMFwgj0pPEhClkRRb/DLpHTjofaBpp681E8EoOWbQz0IFkRYxHB/akTT/AQGI9uSMtQGdigDFZ7Er8dc/gAXQsoxFly3dNpcLOsQR93wR3zzDQeivdIatHaVvvUn4FcNkLMKAiKANFWMJly5BmYvQ=
  app:
    master: castnotice-staging
  on:
    repo: collectiveidea/castnotice
    branch: master
  run:
    - rake db:migrate
    - restart
