development:
  adapter: postgresql
  encoding: unicode
  database: castnotice_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: castnotice_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: castnotice_production
  pool: 5
