development:
  adapter: postgresql
  encoding: unicode
  database: castnotice_development
  user: postgres
  password: postgres
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: castnotice_test
  user: postgres
  password: postgres
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: castnotice_production
  user: postgres
  password: postgres
  pool: 5
